apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 27h
  url: https://charts.bitnami.com/bitnami
  timeout: 2m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system  
spec:
  targetNamespace: ingress-nginx
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: '16.0.6'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1m
  values:
      replicaCount: 2
      service: 
        annotations:    
         service.beta.kubernetes.io/aws-load-balancer-internal: "true" 

